FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -y --fix-missing update
RUN apt-get -y upgrade
RUN apt-get -y install build-essential
RUN apt-get -y install valgrind
RUN apt-get -y install openjdk-8-jdk
RUN apt-get -y install python3 python3-pip
RUN apt-get -y install libboost-all-dev
RUN apt-get -y install git
RUN pip3 install networkx
RUN pip3 install matplotlib
# Ensure ca-certificates is installed and up to date
RUN apt-get -y install ca-certificates
# maven 3.8.6
RUN apt-get -y install wget
RUN wget https://dlcdn.apache.org/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz
RUN tar -xvf apache-maven-3.9.8-bin.tar.gz
RUN mv apache-maven-3.9.8 /opt/
RUN rm apache-maven-3.9.8-bin.tar.gz
ENV PATH="/opt/apache-maven-3.9.8/bin:$PATH"

